/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'KnineRecoveryBounty', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KnineRecoveryBounty__factory>
getContractFactory(name: 'KnineRecoveryBountyDecayAccept', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KnineRecoveryBountyDecayAccept__factory>
getContractFactory(name: 'FalseReturnERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FalseReturnERC20__factory>
getContractFactory(name: 'FeeOnTransferERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FeeOnTransferERC20__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'KnineRecoveryBounty', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KnineRecoveryBounty>
getContractAt(name: 'KnineRecoveryBountyDecayAccept', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KnineRecoveryBountyDecayAccept>
getContractAt(name: 'FalseReturnERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FalseReturnERC20>
getContractAt(name: 'FeeOnTransferERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FeeOnTransferERC20>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'KnineRecoveryBounty', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KnineRecoveryBounty>
deployContract(name: 'KnineRecoveryBountyDecayAccept', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KnineRecoveryBountyDecayAccept>
deployContract(name: 'FalseReturnERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FalseReturnERC20>
deployContract(name: 'FeeOnTransferERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeOnTransferERC20>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'KnineRecoveryBounty', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KnineRecoveryBounty>
deployContract(name: 'KnineRecoveryBountyDecayAccept', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KnineRecoveryBountyDecayAccept>
deployContract(name: 'FalseReturnERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FalseReturnERC20>
deployContract(name: 'FeeOnTransferERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FeeOnTransferERC20>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  